# Generated by Django 4.1.2 on 2022-10-25 09:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='date_released',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.CharField(choices=[('Ls', 'likes'), ('dls', 'dislikes')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
