# Generated by Django 4.1.2 on 2022-10-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_artiste_id_song_date_released_song_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Song_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
