# Generated by Django 4.1.2 on 2022-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_lyric_song_id_lyric_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
